# Generated by Django 4.0.3 on 2022-03-30 12:33

from django.db import migrations, models
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Админ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_guide', models.BooleanField(default=False, verbose_name='Гид')),
                ('is_travel_company', models.BooleanField(default=False, verbose_name='Туристическая компания')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Телефон')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Никнейм')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.models.user_avatar_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
