# Generated by Django 4.0.3 on 2022-03-30 15:45

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_created_alter_user_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default=True, null=True, verbose_name='О гиде')),
                ('count_excursions', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во экскурсий')),
                ('count_guided_tours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во проведенных экскурсий')),
                ('count_reviews', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во отзывов')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Средний рейтинг')),
                ('count_articles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во статей')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='UserGuidePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=users.models.user_guide_photo_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userguide', verbose_name='Гид')),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', imagekit.models.fields.ProcessedImageField(upload_to=users.models.user_guide_certificate_path)),
                ('description', models.TextField(verbose_name='Описание')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userguide', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Сертификат гида',
                'verbose_name_plural': 'Сертификаты гидов',
            },
        ),
    ]
