# Generated by Django 4.0.3 on 2022-03-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userguide_alter_user_options_userguidephoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguide',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
