# Generated by Django 4.0.3 on 2022-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userguide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguide',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О гиде'),
        ),
    ]
