# Generated by Django 4.0.3 on 2022-03-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userguide_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguidephoto',
            options={'verbose_name': 'Фото гида', 'verbose_name_plural': 'Фотографии гидов'},
        ),
    ]
