# Generated by Django 4.0.3 on 2022-03-30 16:24

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userguidephoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguidephoto',
            name='small_photo',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=users.models.user_guide_photo_path),
            preserve_default=False,
        ),
    ]
