# Generated by Django 4.0.3 on 2022-03-30 16:32

from django.db import migrations, models
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userguidephoto_small_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='small_certificate',
            field=imagekit.models.fields.ProcessedImageField(default=3, upload_to=users.models.user_guide_certificate_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='certificate',
            field=models.ImageField(upload_to=users.models.user_guide_certificate_path),
        ),
    ]
