# Generated by Django 4.0.3 on 2022-03-30 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('count_articles', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во статей')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('count_articles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во статей')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('MO', 'Модерация'), ('PU', 'Опубликован'), ('RE', 'Удален')], default='MO', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='TagListPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_published', models.DateField(verbose_name='Дата публикации')),
                ('preview_text', models.TextField(verbose_name='Превью текст')),
                ('detail_text', models.TextField(verbose_name='Текст статьи')),
                ('count_comments', models.PositiveIntegerField(default=0, verbose_name='Кол-во комментариев')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='Теги')),
            ],
        ),
    ]
