# Generated by Django 4.0.3 on 2022-03-31 08:25

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Популярный тег',
                'verbose_name_plural': 'Популярные теги',
                'db_table': 'blog_popular_tag',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[blog.models.validate_name], verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='TagListPopular',
        ),
        migrations.AddField(
            model_name='populartag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='Тег'),
        ),
    ]
