# Generated by Django 4.0.3 on 2022-03-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_average_rating_alter_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='blog_acticle',
        ),
    ]
