# Generated by Django 4.0.3 on 2022-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='3', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(default='3', max_length=255, verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст раздела'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='3', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
