# Generated by Django 4.0.3 on 2022-03-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_description_category_keywords_category_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст раздела'),
        ),
    ]
