# Generated by Django 4.0.3 on 2022-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='SEO - Title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='SEO - Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO - Keywords')),
                ('preview_text', models.TextField(blank=True, verbose_name='Превью описание')),
                ('detail_text', models.TextField(blank=True, verbose_name='Описание экскурсии')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(blank=True, choices=[('PE', 'С человека'), ('TO', 'За экскурсию')], max_length=2, verbose_name='Тип цены')),
                ('children', models.BooleanField(default=True, verbose_name='Можно с детьми')),
                ('max_piople_group', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во людей в группе')),
                ('include', models.JSONField(blank=True, null=True, verbose_name='Что включено')),
                ('not_include', models.JSONField(blank=True, null=True, verbose_name='Что не включено')),
                ('duration_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, в минутах')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Средний рейтинг')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Категория экскурсии',
                'verbose_name_plural': 'Категории экскурсий',
            },
        ),
        migrations.CreateModel(
            name='ExcursionFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.CreateModel(
            name='ExcursionMeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Описание места встречи')),
            ],
            options={
                'verbose_name': 'Место встречи',
                'verbose_name_plural': 'Места встречи',
            },
        ),
        migrations.CreateModel(
            name='ExcursionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Способ передвижения',
                'verbose_name_plural': 'Способы передвижения',
            },
        ),
        migrations.CreateModel(
            name='ExcursionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг от 1 до 5')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('status', models.CharField(choices=[('RE', 'Удален'), ('MO', 'Модерация'), ('PU', 'Опубликован')], max_length=2, verbose_name='Статус отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ExcursionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип экскурсии',
                'verbose_name_plural': 'Типы экскурсий',
            },
        ),
    ]
