# Generated by Django 4.0.3 on 2022-03-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attraction', '0002_initial'),
        ('geo', '0001_initial'),
        ('excursions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionreview',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='excursionreview',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion', verbose_name='Экскурсия'),
        ),
        migrations.AddField(
            model_name='excursionfaq',
            name='author_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursionfaq',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion', verbose_name='Вопрос/Ответ'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='attraction.attraction', verbose_name='Достопримечательности'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='categories',
            field=models.ManyToManyField(to='excursions.excursioncategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='meeting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionmeetingpoint', verbose_name='Место встречи'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excursions.excursionmovement'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region', verbose_name='Область/край'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excursions.excursiontype'),
        ),
    ]
