# Generated by Django 4.0.3 on 2022-03-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название достопримечательности')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='SEO - Title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='SEO - Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO - Keywords')),
                ('preview_text', models.TextField(blank=True, verbose_name='Превью описание')),
                ('detail_text', models.TextField(blank=True, verbose_name='Описание достопримечательности')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='AttractionFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Удален'), ('MO', 'Модерация'), ('PU', 'Опубликован')], max_length=2, verbose_name='Статус вопроса')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.CreateModel(
            name='AttractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип достопримечательности',
                'verbose_name_plural': 'Типы достопримечательностей',
            },
        ),
        migrations.CreateModel(
            name='AttractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг от 1 до 5')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('status', models.CharField(choices=[('RE', 'Удален'), ('MO', 'Модерация'), ('PU', 'Опубликован')], max_length=2, verbose_name='Статус отзыва')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.attraction', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
