# Generated by Django 4.0.3 on 2022-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='count_reviews',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во отзывов'),
        ),
    ]
