# Generated by Django 4.0.3 on 2022-03-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0004_remove_attraction_type_attraction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='type',
            new_name='types',
        ),
    ]
