# Generated by Django 4.0.3 on 2022-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_rename_type_attraction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='types',
            field=models.ManyToManyField(blank=True, to='attraction.attractiontype', verbose_name='Тип достопримечательности'),
        ),
    ]
