# Generated by Django 4.0.3 on 2022-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
                ('og', models.JSONField(blank=True, verbose_name='Open Graph разметка')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='SeoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('keywords', models.CharField(max_length=255, verbose_name='Keywords')),
                ('type', models.CharField(max_length=255, unique=True, verbose_name='Тип, берем из get=types')),
                ('og', models.JSONField(blank=True, verbose_name='Open Graph разметка')),
                ('helper', models.TextField(verbose_name='Описание шаблона для админа')),
            ],
            options={
                'verbose_name': 'SEO шаблон',
                'verbose_name_plural': 'SEO шаблоны',
            },
        ),
    ]
